spring:
  application:
    name: dubbo-customer

server:
  port: 8010

dubbo:
  application:
    id: dubbo-customer # 当前dubbo应用id
    name: dubbo-customer # 当前dubbo应用名称
  registry:
    address: zookeeper://127.0.0.1:2181 # 注册中心
    timeout: 60000
    group: dubbo
    check: false
  protocol:
    id: dubbo-provider # 生产者提供的协议id
    name: dubbo # 生产者暴露给消费者协议
    port: 20880 # 生产者暴露给消费者端口

logging:
  config: classpath:log4j2.xml

